call activate robo-project-py3.7
pip install pandas
pip install opencv-python
pip install tensorflow
pip install keras
pip install numpy
pip install matplotlib
pip install websockets
pip install pyttsx3
pip install pypiwin32